In [3]:
import tensorflow
import numpy as np

from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import errors_impl
from tensorflow.python.framework import ops
from tensorflow.python.keras import backend
#from tensorflow.python.keras import combinations
from tensorflow.python.keras import losses
from tensorflow.python.keras.utils import losses_utils
from tensorflow.python.platform import test

ALL_LOSSES = [
    losses.mean_squared_error, losses.mean_absolute_error,
    losses.mean_absolute_percentage_error,
    losses.mean_squared_logarithmic_error, losses.squared_hinge, losses.hinge,
    losses.categorical_crossentropy, losses.binary_crossentropy,
    losses.kullback_leibler_divergence, losses.poisson,
    losses.cosine_similarity, losses.logcosh, losses.categorical_hinge
]

In [10]:
y_a = backend.variable(np.random.random((5, 6, 7)))
y_b = backend.variable(np.random.random((5, 6, 7)))
for obj in ALL_LOSSES:
    objective_output = obj(y_a, y_b)
    #print(objective_output.shape.as_list())

In [17]:
mse_obj = losses.MeanSquaredError()
true = [1, 9, 2, -5, -2, 6]
pred = [4, 8, 12, 8, 1, 3]
y_true = constant_op.constant(true, shape=(2, 3))
y_pred = constant_op.constant(pred,
                                  shape=(2, 3),
                                  dtype=dtypes.float32)
loss = mse_obj(y_true, y_pred)
print(loss)

tf.Tensor(49.5, shape=(), dtype=float32)


In [19]:
y = true
y_bar = pred
summation = 0  #variable to store the summation of differences
n = len(y) #finding total number of items in list
for i in range (0,n):  #looping through each element of the list
  difference = y[i] - y_bar[i]  #finding the difference between observed and predicted value
  squared_difference = difference**2  #taking square of the differene 
  summation = summation + squared_difference  #taking a sum of all the differences
MSE = summation/n  #dividing summation by total values to obtain average
print("The Mean Square Error is: " + str(MSE))

The Mean Square Error is: 49.5


## Binary Cross Entropy

In [44]:
target = backend.variable(np.random.randint(0, 2, (5, 1)))
logits = backend.variable(np.random.random((5, 1)))
sigmoid_output = backend.sigmoid(logits)

In [45]:
#np.random.randint(2, size=10)

In [46]:
target

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [0.],
       [1.]], dtype=float32)>

In [47]:
logits

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.31217206],
       [0.96582544],
       [0.66500735],
       [0.48153389],
       [0.02099748]], dtype=float32)>

In [48]:
sigmoid_output

<tf.Tensor: id=936, shape=(5, 1), dtype=float32, numpy=
array([[0.57741535],
       [0.7242866 ],
       [0.6603843 ],
       [0.61811   ],
       [0.5052492 ]], dtype=float32)>

In [49]:
output_from_logit = losses.binary_crossentropy(
        target, logits, from_logits=True)
output_from_sigmoid = losses.binary_crossentropy(target, sigmoid_output)

In [50]:
output_from_logit

<tf.Tensor: id=953, shape=(5,), dtype=float32, numpy=
array([0.54919344, 0.32256806, 0.41493332, 0.9626227 , 0.68270355],
      dtype=float32)>

In [51]:
output_from_sigmoid

<tf.Tensor: id=977, shape=(5,), dtype=float32, numpy=
array([0.5491932 , 0.3225679 , 0.41493317, 0.96262246, 0.68270326],
      dtype=float32)>

Categorical Cross Entropy with 

In [69]:
t = backend.placeholder()
p = backend.placeholder()
cce = losses.sparse_categorical_crossentropy(t, p)

t_val = ops.convert_to_tensor_v2([0, 1, 2, 3])
p_val = ops.convert_to_tensor_v2([[.9, .05, .025,0.025],[.05, .89, .03,0.03],[.04, .01, .94,0.01],
                                  [.02, .02, .01,0.95]])

f = backend.function([t, p], cce)

result = f([t_val, p_val])

In [70]:
result

array([0.10536056, 0.11653379, 0.06187528, 0.05129333], dtype=float32)

In [60]:
import tensorflow as tf
cce = tf.keras.losses.CategoricalCrossentropy()
loss = cce(
  [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]],
  [[.9, .05, .05], [.05, .89, .06], [.05, .01, .94]])
print('Loss: ', loss.numpy())

Loss:  0.09458993
